Failure # 1 (occurred at 2024-02-15_13-42-39)
The actor died because of an error raised in its creation task, [36mray::PPO.__init__()[39m (pid=22629, ip=172.23.148.251, actor_id=a9d3efc320ef2be609ef4d6101000000, repr=PPO)
  File "/home/kuros/.local/lib/python3.10/site-packages/ray/rllib/evaluation/worker_set.py", line 229, in _setup
    self.add_workers(
  File "/home/kuros/.local/lib/python3.10/site-packages/ray/rllib/evaluation/worker_set.py", line 616, in add_workers
    raise result.get()
  File "/home/kuros/.local/lib/python3.10/site-packages/ray/rllib/utils/actor_manager.py", line 487, in __fetch_result
    result = ray.get(r)
ray.exceptions.RayActorError: The actor died because of an error raised in its creation task, [36mray::RolloutWorker.__init__()[39m (pid=22727, ip=172.23.148.251, actor_id=51f7baad54ebf57eb4e2554a01000000, repr=<ray.rllib.evaluation.rollout_worker.RolloutWorker object at 0x7fa3dd7d5210>)
  File "/home/kuros/.local/lib/python3.10/site-packages/gymnasium/envs/registration.py", line 740, in make
    env_spec = _find_spec(id)
  File "/home/kuros/.local/lib/python3.10/site-packages/gymnasium/envs/registration.py", line 537, in _find_spec
    _check_version_exists(ns, name, version)
  File "/home/kuros/.local/lib/python3.10/site-packages/gymnasium/envs/registration.py", line 403, in _check_version_exists
    _check_name_exists(ns, name)
  File "/home/kuros/.local/lib/python3.10/site-packages/gymnasium/envs/registration.py", line 380, in _check_name_exists
    raise error.NameNotFound(
gymnasium.error.NameNotFound: Environment `pursuit_v4` doesn't exist.

During handling of the above exception, another exception occurred:

[36mray::RolloutWorker.__init__()[39m (pid=22727, ip=172.23.148.251, actor_id=51f7baad54ebf57eb4e2554a01000000, repr=<ray.rllib.evaluation.rollout_worker.RolloutWorker object at 0x7fa3dd7d5210>)
  File "/home/kuros/.local/lib/python3.10/site-packages/ray/rllib/evaluation/rollout_worker.py", line 407, in __init__
    self.env = env_creator(copy.deepcopy(self.env_context))
  File "/home/kuros/.local/lib/python3.10/site-packages/ray/rllib/env/utils.py", line 177, in _gym_env_creator
    raise EnvError(ERR_MSG_INVALID_ENV_DESCRIPTOR.format(env_descriptor))
ray.rllib.utils.error.EnvError: The env string you provided ('pursuit_v4') is:
a) Not a supported/installed environment.
b) Not a tune-registered environment creator.
c) Not a valid env class string.

Try one of the following:
a) For Atari support: `pip install gym[atari] autorom[accept-rom-license]`.
   For VizDoom support: Install VizDoom
   (https://github.com/mwydmuch/ViZDoom/blob/master/doc/Building.md) and
   `pip install vizdoomgym`.
   For PyBullet support: `pip install pybullet`.
b) To register your custom env, do `from ray import tune;
   tune.register('[name]', lambda cfg: [return env obj from here using cfg])`.
   Then in your config, do `config['env'] = [name]`.
c) Make sure you provide a fully qualified classpath, e.g.:
   `ray.rllib.examples.env.repeat_after_me_env.RepeatAfterMeEnv`

During handling of the above exception, another exception occurred:

[36mray::PPO.__init__()[39m (pid=22629, ip=172.23.148.251, actor_id=a9d3efc320ef2be609ef4d6101000000, repr=PPO)
  File "/home/kuros/.local/lib/python3.10/site-packages/ray/rllib/algorithms/algorithm.py", line 516, in __init__
    super().__init__(
  File "/home/kuros/.local/lib/python3.10/site-packages/ray/tune/trainable/trainable.py", line 161, in __init__
    self.setup(copy.deepcopy(self.config))
  File "/home/kuros/.local/lib/python3.10/site-packages/ray/rllib/algorithms/algorithm.py", line 638, in setup
    self.workers = WorkerSet(
  File "/home/kuros/.local/lib/python3.10/site-packages/ray/rllib/evaluation/worker_set.py", line 181, in __init__
    raise e.args[0].args[2]
ray.rllib.utils.error.EnvError: The env string you provided ('pursuit_v4') is:
a) Not a supported/installed environment.
b) Not a tune-registered environment creator.
c) Not a valid env class string.

Try one of the following:
a) For Atari support: `pip install gym[atari] autorom[accept-rom-license]`.
   For VizDoom support: Install VizDoom
   (https://github.com/mwydmuch/ViZDoom/blob/master/doc/Building.md) and
   `pip install vizdoomgym`.
   For PyBullet support: `pip install pybullet`.
b) To register your custom env, do `from ray import tune;
   tune.register('[name]', lambda cfg: [return env obj from here using cfg])`.
   Then in your config, do `config['env'] = [name]`.
c) Make sure you provide a fully qualified classpath, e.g.:
   `ray.rllib.examples.env.repeat_after_me_env.RepeatAfterMeEnv`
